spring:
  application:
    name: file-service

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      ddlAuto: validate
    open-in-view: true