package com.coursework.account_management_service.infrastructure.persistence

import com.coursework.account_management_service.infrastructure.model.CurrencyInUserPossessionEntity
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository

@Repository
interface CurrencyInUserPossessionRepository: JpaRepository<CurrencyInUserPossessionEntity, Long>